### PR TITLE
Remove nbconvert-webpdf, add nbconvert-qtpdf

### PR DESCRIPTION
**Pull request by bollwyvl**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

- removes broken `nbconvert-webpdf`.
  - leaves notes pointing at https://github.com/conda-forge/staged-recipes/issues/23382

As a follow-up to https://github.com/conda-forge/nbconvert-feedstock/pull/108#issuecomment-1638403173  `nbconvert-webpdf 7.7.1=*_0` should be marked broken.

### CODE REVIEW

**Comment by bollwyvl** [comment]
Will see if it's reasonable to add `qtpdf`...

**Comment by bollwyvl** [comment]
`nbconvert-qtpdf` builds locally, but might need some `yum.txt` help on CI... will investigate further.

**Comment by bollwyvl** [comment]
@conda-forge-admin please rerender

**Comment by bollwyvl** [comment]
@conda-forge-admin please rerender

**Comment by bollwyvl** [comment]
@conda-forge/nbconvert ready for review

**Comment by blink1073** [comment]
Thank you!

**Pull request merged**
