### PR TITLE
Update meta.yaml - add pandoc max version #94

### PR DESCRIPTION
**Pull request by achimgaedke**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)

implements fix for #94 - did not bumb the build number as I would belive it is not high priority.

### CODE REVIEW

**Review by martinRenou — APPROVED** [review]
LGTM! We may want to push a PR to https://github.com/conda-forge/conda-forge-repodata-patches-feedstock, more specifically [to this file](https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/blob/main/recipe/gen_patch_json.py) for patching any previous nbconvert entry on conda-forge.

**Comment by bollwyvl** [comment]
Good find. Ideally this would add a test that actually would hit that version check, likely more robust than trying to parse it out from wherever the problem is.

**Comment by achimgaedke** [comment]
Would be https://conda.io/projects/conda-build/en/stable/resources/define-metadata.html#loading-data-from-other-files the right mechanism for it?

```
{% set min_version = load_file_regex(
    load_file='nbconvert/utils/pandoc.py',
    regex_pattern=r'^_minimal_version\s*=\s*"(\S+)"') %}
```

and the same for the maximal version, add both strings using jinja to the appropriate pandoc requirements line.

Following the comments, line 80 seemed to be the correct position.l

**Comment by achimgaedke** [comment]
As pandoc is not a python/pip package the requirements are not formalized in any other file. Managing the requirements in this case is the reason for (re-)package managers like conda-forge. 😸

**Comment by bollwyvl** [comment]
Using "fancy" Jinja for requirements breaks some of the bot features, so it
won't even get prs: tests are generally more reliable, and hard coded
values are easier to track when things change.

For example:

    - python -c "p = __import__('nbconvert. pandoc').pandoc; assert
(p._min_pandoc, p._max_pandoc)==('{{ min_pandoc }},'{{ max_pandoc }}')"

**Comment by achimgaedke** [comment]
That makes sense, but templates were the first thing I stumbled over in the docs.
I'm curious to see the worked-out solution, I'll be offline for some days.

**Comment by achimgaedke** [comment]
Ah, just saw https://github.com/conda-forge/nbconvert-feedstock/pull/96 - but already started to build "my own"... should have read the thread more carefully.

Awesome to see it grow... @bollwyvl has a separate python test file instead of an unwieldy command line -> #96 is better

**Pull request closed without merging**
