### PR TITLE
Test for pandoc version range

### PR DESCRIPTION
**Pull request by bollwyvl**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

References:
- ensures future versions don't regress on #94
- alternative to #95

Changes:
- [x] adds a script to print and check the pandoc version against the as-imported library
  - [x] see a failure in CI
- [x] update specs, see failure go away
  - [ ] add top pin of `3.0.0`
- [ ] figure out longer-term plan
  - run full `test` suite?
  - run a `downstream` test that uses pandoc?
  - advocate upstream for a more canonical/public place to store the pandoc range

### CODE REVIEW

**Comment by bollwyvl** [comment]
@conda-forge-admin please rerender

**Comment by bollwyvl** [comment]
A fail will look like:

```
+ python check_pandoc.py '>=1.12.1' '<'
Comparing recipe spec and nbconvert for pandoc:
... PANDOC VERSION       
pandoc 3.1.1
Features: +server +lua
Scripting engine: Lua 5.4
User data directory: /home/conda/.local/share/pandoc
Copyright (C) 2006-2023 John MacFarlane. Web:  https://pandoc.org/
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.

... RECIPE PANDOC SPEC    ('>=1.12.1', '<')
Traceback (most recent call last):
  File "/home/conda/feedstock_root/build_artifacts/nbconvert-meta_1679723921095/test_tmp/check_pandoc.py", line 18, in <module>
    assert recipe_spec == pandoc_spec
AssertionError
... NBCONVERT PANDOC SPEC ('>=1.12.1', '<3.0.0')
Tests failed for nbconvert-pandoc-7.2.10-pyhd8ed1ab_1.conda - moving package to /home/conda/feedstock_root/build_artifacts/broken
```

**Comment by bollwyvl** [comment]
A passing test:

```

2023-03-25T14:49:43.3922964Z + python check_pandoc.py '>=1.12.1' '<3.0.0'
2023-03-25T14:49:43.4030380Z Comparing recipe spec and nbconvert for pandoc:
2023-03-25T14:49:43.4158367Z ... PANDOC VERSION       
2023-03-25T14:49:43.4306346Z pandoc 2.19.2
2023-03-25T14:49:43.4307417Z Compiled with pandoc-types 1.22.2.1, texmath 0.12.5.2, skylighting 0.13,
2023-03-25T14:49:43.4308006Z citeproc 0.8.0.1, ipynb 0.2, hslua 2.2.1
2023-03-25T14:49:43.4308447Z Scripting engine: Lua 5.4
2023-03-25T14:49:43.4308879Z User data directory: /home/conda/.local/share/pandoc
2023-03-25T14:49:43.4309484Z Copyright (C) 2006-2022 John MacFarlane. Web:  https://pandoc.org
2023-03-25T14:49:43.4310031Z This is free software; see the source for copying conditions. There is no
2023-03-25T14:49:43.4310601Z warranty, not even for merchantability or fitness for a particular purpose.
2023-03-25T14:49:43.4310921Z 
2023-03-25T14:49:43.4311412Z ... RECIPE PANDOC SPEC    ('>=1.12.1', '<3.0.0')
2023-03-25T14:49:43.7884427Z ... NBCONVERT PANDOC SPEC ('>=1.12.1', '<3.0.0')
2023-03-25T14:49:43.8445046Z + exit 0
2023-03-25T14:49:45.1434413Z 
```

**Comment by bollwyvl** [comment]
@conda-forge/nbconvert ready for review. if this is good, then we can work on the repodata patch. might take a little digging to find the right versions.

**Comment by bollwyvl** [comment]
Looks like the epochs are: 
- `<5.5.0`
  - `>=1.2.1,<2.0.0`
- `>=5.5.0`
  - `>=1.2.1,<3.0.0`

**Comment by achimgaedke** [comment]
Looks good to me, this PR would fix #94

**Comment by bollwyvl** [comment]
The repodata PR was merged to fix historical version pins:

https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/424

**Pull request merged**
