### PR TITLE
nbconvert 6.4.0

### PR DESCRIPTION
**Pull request by bollwyvl**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by bollwyvl** [comment]
conda-forge-admin, please rerender

**Comment by bollwyvl** [comment]
Boo:

```
+LDFLAGS=-Wl,-O2 -Wl,--sort-common -Wl,--as-needed -Wl,-z,relro -Wl,-z,now -Wl,-rpath,$PREFIX/lib -Wl,-rpath-link,$PREFIX/lib -L$PREFIX/lib
Setting up cross-python
ERROR: local variable 'lines' referenced before assignment
Traceback (most recent call last):
  File "/opt/conda/bin/conda-mambabuild", line 10, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.8/site-packages/boa/cli/mambabuild.py", line 215, in main
    call_conda_build(action, config)
  File "/opt/conda/lib/python3.8/site-packages/boa/cli/mambabuild.py", line 187, in call_conda_build
    result = api.build(
  File "/opt/conda/lib/python3.8/site-packages/conda_build/api.py", line 186, in build
    return build_tree(
  File "/opt/conda/lib/python3.8/site-packages/conda_build/build.py", line 3083, in build_tree
    packages_from_this = build(metadata, stats,
  File "/opt/conda/lib/python3.8/site-packages/conda_build/build.py", line 2206, in build
    utils.check_call_env(cmd, env=env, rewrite_stdout_env=rewrite_env,
  File "/opt/conda/lib/python3.8/site-packages/conda_build/utils.py", line 410, in check_call_env
    return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/conda_build/utils.py", line 390, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/home/conda/feedstock_root/build_artifacts/nbconvert_1641311293885/work/conda_build.sh']' returned non-zero exit status 1.
##[error]Bash exited with code '1'.
Finishing: Run docker build

```

**Comment by blink1073** [comment]
Yeah I'm not sure where that is coming from.  I looked at the `nbconvert` source and all I found was [this](https://github.com/jupyter/nbconvert/blob/4607ed2078f38a63d055e76307d9f66f32e8a5fd/nbconvert/filters/strings.py#L193), which I don't think could cause the error.

**Comment by bollwyvl** [comment]
Perhaps from here?

https://github.com/benfogle/crossenv/blob/56ddd69bf0c81d0c494bc1ecc502eec784e0e50f/crossenv/__init__.py#L351

I'll try writing out an empty `Makefile`... can't hurt...

**Comment by bollwyvl** [comment]
Ah, https://github.com/benfogle/crossenv/pull/85

**Comment by bollwyvl** [comment]
Looks like upstream should be fixed... will revert that Makefile jank...

**Comment by bollwyvl** [comment]
@conda-forge-admin please rerender

**Comment by bollwyvl** [comment]
Welp, those are passing. LGTM otherwise (provided windows passes)

**Comment by bollwyvl** [comment]
Ah, and I'm not a maintainer. Happy to add self as a follow-on, or on here, but figure we take the builds and run if they work...

**Comment by bollwyvl** [comment]
@conda-forge/nbconvert we are all :green_circle: happy new year!

**Comment by blink1073** [comment]
Thanks @bollwyvl, nice work!  I found out recently that this is a new preferred way to [add yourself as a maintainer](https://conda-forge.org/docs/maintainer/infrastructure.html#conda-forge-admin-please-add-user-username).

**Pull request merged**
