### PR TITLE
release 5.3.1

### PR DESCRIPTION
**Pull request by mpacer**
Patch release.

### CODE REVIEW

**Comment by jakirkham** [comment]
Could also use a [re-rendering]( https://github.com/conda-forge/conda-smithy#re-rendering-an-existing-feedstock ) with `conda-smithy` 2.4.0. May be worth adding [`noarch: python`]( https://conda.io/docs/user-guide/tasks/build-packages/define-metadata.html#architecture-independent-packages ) before re-rendering.

**Comment by takluyver** [comment]
Is noarch recommended again now? I asked before and it was considered deprecated.

**Comment by ocefpaf** [comment]
> Is noarch recommended again now? I asked before and it was considered deprecated.

It is not deprecated but I do not recommend using it here until we know how conda will handle the entrypoints in that scenario.

**Comment by jakirkham** [comment]
`noarch_python: true` is being deprecated. `noarch: python` is supported.

That said, @ocefpaf just asked a great question on [gitter]( https://gitter.im/conda-forge/conda-forge.github.io?at=59afea188f4427b462dacc94 ) about entry points, which I don't know the answer to. Would be good to hear back from @msarahan and/or @jjhelmus on this point.

**Comment by jakirkham** [comment]
Also copying @kalefranz.

**Comment by takluyver** [comment]
FYI, I did a bit more development on [flonda](https://pypi.python.org/pypi/flonda) as an alternative to noarch Python packages. It can build conda packages for a pure Python library, for different platforms and Python versions from a single machine. Still experimental (is there any documentation on what a conda package needs to contain?), but it's worked in my tests.

**Comment by mpacer** [comment]
I rerendered with conda-smithy, but I didn't do the noarch change because I don't know the full context of what that means. Given the context and the crucial place of entrypoints in nbconvert I'm hesitant to do anything that might break them.

**Comment by ocefpaf** [comment]
@mpacer I understand your concern and I agree with you. However, I did a few tests with `noarch` and entrypoints and everything worked, so here is what I propose we do here:

- merge this even before we can check Travis-CI to get Windows and Linux packages out there; It is highly unlikely Travis-CI OS X will fail and we cannot afford to keep waiting for Travis-CI OS X to get back online;
- as soon as this is merged I'll send a PR with the `noarch` option and, if we get failure reports, we can pull the packages (not a big deal b/c we'll have the ones from this PR to fallback).

Is that OK? If so let me know and I'll merge this and move with the plan.

**Comment by jjhelmus** [comment]
I'm in support of @ocefpaf's plan for merging and updating to `noarch`.  As a data point, I've been building `nbconvert` as a `noarch: python` [package in berryconda](https://github.com/jjhelmus/berryconda/tree/master/recipes/nbconvert) since version 5.2.1 and have not run into any issues.

**Comment by ocefpaf** [comment]
Let's go for it then. Delay the release b/c of Travis-CI is quite annoying.

**Pull request merged**
