### PR TITLE
release 5.0

### PR DESCRIPTION
**Pull request by minrk**
will need to wait for pandocfilters recipe to be staged (https://github.com/conda-forge/staged-recipes/pull/2087)

### CODE REVIEW

**Comment by minrk** [comment]
The next thing missing is testpath, which is causing some difficulty because it uses `flit`. @takluyver any objection to making testpath use normal setup rather than flit now that it's a real dependency, so that packaging/installing it is easier?

**Comment by takluyver** [comment]
I'm working on the PEPs (517, 518) to do installation from source without needing setup.py. Hopefully I'll get some chances over Christmas to push this forwards. So I'd rather not give up and go back to setuptools.

We already have entrypoints in conda-forge without a setup.py file, so it's not an insurmountable obstacle.

**Comment by minrk** [comment]
Would you be okay running and uploading the result of your [make_sdist script](https://gist.github.com/takluyver/7c66429a8e7f2b9388b0) for testpath (and entrypoints, ideally)? The result of that seems really nice, and what I would want from pretty much everything packaged with flit.

**Comment by takluyver** [comment]
There's an experimental sdist branch on flit, but you've now got testpath working in conda-forge (https://github.com/conda-forge/testpath-feedstock ) anyway, is this ready to move forwards?

Feel free to add myself and @michaelpacer as maintainers on this feedstock.

**Comment by michaelpacer** [comment]
I'm going to make a new PR just because it looks like the CI builds have failed and need to be rerun (so that if there are any more errors, then I can try to address them), and since I'm not yet a maintainer here, I cannot rerun them. If there's not anything that needs changing, I'll just close that PR and ping thing one.

**Comment by michaelpacer** [comment]
I just saw that the travis builds are not completing on this repo either :(. Any thoughts as to why?

**Comment by jakirkham** [comment]
...because of the backlog. 😒

screen shot 2017-01-19 at 19 36 44

**Comment by michaelpacer** [comment]
One of the things that worries me is that it says the backlog has cleared, but the first of the series of builds (https://travis-ci.org/conda-forge/nbconvert-feedstock/builds/193489401) hasn't even begun.

**Comment by jakirkham** [comment]
> ... it says the backlog has cleared...

Where does it say this? Still showing ~600 builds queued FWICT.

**Comment by michaelpacer** [comment]
Their text suggested that from their perspective it had cleared, I agree with you since ~600 builds to me also means "has not been cleared". Maybe they mean something different by "cleared"?

image

**Comment by michaelpacer** [comment]
It's not clear to me that the `jupyter_client` dependency is unwarranted given that we do rely on it for the execute preprocessor. I'm guessing that @minrk has a solution to executing notebooks without the `jupyter_client.KernelManager` class that I just can't think of.

**Comment by minrk** [comment]
jupyter_client is an 'optional' dependency, in that it's only required for a small, infrequently used portion (`--execute`), and potentially an expensive dependency, due to the incorporation of compiled dependencies like zeromq. This is less important for the conda package than it is for the pip package. It's already fixed in nbconvert master, so I was just making a note that it's a bug that's been fixed upstream already, and the dependency can be removed in the next release.

**Comment by michaelpacer** [comment]
I am still a little confused, though I think I understand. 

I'm looking at our setup.py from the 5.0.0 release and we have the only place `jupyter_client` appears is as a [dependency for the `extras_require["execute"]`](https://github.com/jupyter/nbconvert/blob/5.0.0/setup.py#L205). However, there is a bare import of it that was removed with https://github.com/jupyter/nbconvert/commit/f361022bf61666d8ffe517690dfb7e6200a5905b, instead replaced with traitlet cleverness that can treat a string with `.` in it as a module specification to load it on the fly.

That's why it then needed to then be added as an explicit test dependency (with https://github.com/jupyter/nbconvert/commit/ca022848b82fd0e23b07017c55c0c006b91b19f5) since otherwise we could not guarantee that the tests would run (because it wouldn't build with `jupyter_client` if being installed in an empty environment, despite being needed for the tests). However, that means that because tests are required with every conda forge package (as part of the CI integration, from what I can tell) it will still need to be a part of the conda-forge build. However, because PyPI doesn't require running tests or CI integration, we don't need to involve it there. 

Ok good to know. 

If I were to release a 5.1 or a 5.0.1 tomorrow, would we still want to complete the 5.0.0 release on conda-forge for those who would want it? Or will it be like 4.3 and skipped over entirely by updating this PR to have the more recent version number? I just don't know which is preferable.

**Comment by minrk** [comment]
> If I were to release a 5.1 or a 5.0.1 tomorrow, would we still want to complete the 5.0.0 release on conda-forge for those who would want it? Or will it be like 4.3 and skipped over entirely by updating this PR to have the more recent version number? I just don't know which is preferable.

If we haven't finished getting 5.0 working by the time you finish pushing 5.1 to PyPI, I'm happy updating here. I don't think it's critical that every release get pushed to conda-forge.

**Comment by michaelpacer** [comment]
Ok, well, the CI still hasn't cleared despite the backlog being supposedly taken care of:

image

It won't hurt to do another push, since it'll enter and there's no current queue. I'll release nbconvert 5.1 and we can get it on conda-forge pretty immediately.

**Pull request merged**
