### PR TITLE
rerender

### LINKED ISSUE #3: Missing dependency on six?
I just got this while trying to export a notebook to PDF in the notebook UI: `Could not construct Exporter: No module named 'six'.`

Installing six into the conda environment which contained the notebook server and nbconvert fixed the problem. This issue is placed here because I think that nbconvert is called directly via the python modules: https://github.com/jupyter/notebook/blob/32011e3bad2aad1bb49557dbf5c58bf973e44ab0/notebook/nbconvert/handlers.py#L56-L73

Here is the log:

```
[W 13:37:34.977 NotebookApp] 500 GET /nbconvert/pdf/Editors_5_Analysis_R_unmatch
ed.ipynb?download=true (::1): Could not construct Exporter: No module named 'six
'
[E 13:37:34.985 NotebookApp] {
      "Accept-Encoding": "gzip, deflate, sdch",
      "Upgrade-Insecure-Requests": "1",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8",
      "Referer": "http://localhost:8888/notebooks/Editors_5_Analysis_R_unmatched.ipynb",
      "Accept-Language": "de-DE,de;q=0.8,en-US;q=0.6,en;q=0.4",
      "Connection": "keep-alive",
      "Host": "localhost:8888",
      "User-Agent": "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36",
      "Cookie": "gsScrollPos="
    }
[E 13:37:34.987 NotebookApp] 500 GET /nbconvert/pdf/Editors_5_Analysis_R_unmatch
ed.ipynb?download=true (::1) 691.04ms referer=http://localhost:8888/notebooks/Ed
itors_5_Analysis_R_unmatched.ipynb
```

### PR DESCRIPTION
**Pull request by ocefpaf**
Closes #3

### CODE REVIEW

**Comment by minrk** [comment]
I don't think nbconvert uses six. #3 might be misleading due to a truncated error message.

**Comment by ocefpaf** [comment]
> I don't think nbconvert uses six. #3 might be misleading due to a truncated error message.

Thanks @minrk! I removed the "add six" commit and left the just "rerender."

@janschulz can you take a look at that and close #3?

**Comment by janschulz** [comment]
#3 is closed, so I don't know if the rerender is still necessary or not.

**Comment by jakirkham** [comment]
Re-rendering is generally a good thing so don't think it causes any problems to continue with it.

**Pull request merged**
