### PR TITLE
nbconvert 6.4.3

### PR DESCRIPTION
**Pull request by bollwyvl**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Notes:
- adds self as maintainer

### CODE REVIEW

**Comment by bollwyvl** [comment]
@conda-grayskull show requirements

**Comment by conda-grayskull** [comment]
Working on your request...

**Comment by conda-grayskull** [comment]
================ **BUILD** ================
Requirements for **build**
| Current Deps | Grayskull found |  |
|--------------|-----------------|--|
| python  # [build_platform != target_platform] |  | :x: |
| cross-python_<{ target_platform }}  # [build_platform != target_platform] |  | :x: |


================ **HOST** ================
Requirements for **host**
| Current Deps | Grayskull found |  |
|--------------|-----------------|--|
| python | python >=3.7 | :heavy_exclamation_mark: |
| pip | pip | :heavy_check_mark: |


================ **RUN** ================
Requirements for **run**
| Current Deps | Grayskull found |  |
|--------------|-----------------|--|
| python | python >=3.7 | :heavy_exclamation_mark: |
| mistune >=0.8.1,<2 | mistune >=0.8.1,<2 | :heavy_check_mark: |
| jinja2 >=2.4 | jinja2 >=2.4 | :heavy_check_mark: |
| pygments >=2.4.1 | pygments >=2.4.1 | :heavy_check_mark: |
| traitlets >=5.0 | traitlets >=5.0 | :heavy_check_mark: |
| jupyter_core | jupyter_core | :heavy_check_mark: |
| nbformat >=4.4 | nbformat >=4.4 | :heavy_check_mark: |
| entrypoints >=0.2.2 | entrypoints >=0.2.2 | :heavy_check_mark: |
| bleach | bleach | :heavy_check_mark: |
| pandocfilters >=1.4.1 | pandocfilters >=1.4.1 | :heavy_check_mark: |
| testpath | testpath | :heavy_check_mark: |
| defusedxml | defusedxml | :heavy_check_mark: |
| pandoc >=1.12.1  # [x86] |  | :x: |
| nbclient >=0.5.0,<0.6.0 | nbclient >=0.5.0,<0.6.0 | :heavy_check_mark: |
| jupyterlab_pygments | jupyterlab_pygments | :heavy_check_mark: |

**Review by blink1073 — APPROVED** [review]
LGTM!

**Comment by bollwyvl** [comment]
ha, i'm not a maintainer. might as well...

**Pull request merged**
