### PR TITLE
Add jasongrout to maintainers

### PR DESCRIPTION
**Pull request by jasongrout**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

I'm publishing the 6.2.0 release, and would like to publish an 6.2.0rc0 conda-forge package to match the pypi RC I just released. I think I need to be a contributor in order to create an RC branch for the 6.2.0rc0 package. I'd also like to help update this feedstock for the 6.2.0 final release.

### CODE REVIEW

**Comment by jasongrout** [comment]
@conda-forge-admin, please rerender

**Review by blink1073 — APPROVED** [review]
👍🏼

**Comment by jasongrout** [comment]
@mseal @blink1073 (or another maintainer) - can I be made a maintainer to help with the upcoming 6.2.0 conda-forge release, and to publish a conda-forge RC release?

**Comment by jasongrout** [comment]
> **[blink1073](/blink1073) ** left a comment

Fastest keyboard in the west!

**Pull request merged**
